### ISSUE TITLE
investigate illegal argument exception exception

### ISSUE THREAD

**Issue by carocad** [n7a235/service.routing#46]
Sometimes when running an autogenerated graph, the app throws an error:

```
{
  "type": "unknown-exception",
  "class": "java.lang.IllegalArgumentException"
}
```

Here is the full stacktrace
```
2017-09-08T12:27:38.750198+00:00 app[web.1]: ERROR No implementation of method: :way of protocol: #'service.routing.graph.protocols/Routable found for class: nil

2017-09-08T12:27:38.750644+00:00 app[web.1]: java.lang.IllegalArgumentException: No implementation of method: :way of protocol: #'service.routing.graph.protocols/Routable found for class: nil

2017-09-08T12:27:38.750894+00:00 app[web.1]: 	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)

2017-09-08T12:27:38.750948+00:00 app[web.1]: 	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)

2017-09-08T12:27:38.750994+00:00 app[web.1]: 	at service.routing.graph.protocols$fn__12028$G__12023__12033.invoke(protocols.clj:59)

2017-09-08T12:27:38.751019+00:00 app[web.1]: 	at service.routing.directions$wayver.invokeStatic(directions.clj:27)

2017-09-08T12:27:38.751058+00:00 app[web.1]: 	at service.routing.directions$wayver.invoke(directions.clj:24)

2017-09-08T12:27:38.751112+00:00 app[web.1]: 	at service.routing.directions$partition_by_street_name$fn__13874.invoke(directions.clj:76)

2017-09-08T12:27:38.751115+00:00 app[web.1]: 	at clojure.lang.AFn.applyToHelper(AFn.java:156)

2017-09-08T12:27:38.751144+00:00 app[web.1]: 	at clojure.lang.AFn.applyTo(AFn.java:144)

2017-09-08T12:27:38.751174+00:00 app[web.1]: 	at clojure.core$apply.invokeStatic(core.clj:659)

2017-09-08T12:27:38.751205+00:00 app[web.1]: 	at clojure.core$map$fn__5402$fn__5403.doInvoke(core.clj:2724)

2017-09-08T12:27:38.751233+00:00 app[web.1]: 	at clojure.lang.RestFn.applyTo(RestFn.java:142)

2017-09-08T12:27:38.751263+00:00 app[web.1]: 	at clojure.lang.TransformerIterator.step(TransformerIterator.java:77)

2017-09-08T12:27:38.751324+00:00 app[web.1]: 	at clojure.lang.TransformerIterator.hasNext(TransformerIterator.java:97)

2017-09-08T12:27:38.751348+00:00 app[web.1]: 	at clojure.lang.RT$4.invoke(RT.java:512)

2017-09-08T12:27:38.751373+00:00 app[web.1]: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)

2017-09-08T12:27:38.751419+00:00 app[web.1]: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)

2017-09-08T12:27:38.751447+00:00 app[web.1]: 	at clojure.lang.LazySeq.next(LazySeq.java:78)

2017-09-08T12:27:38.751477+00:00 app[web.1]: 	at clojure.lang.RT.next(RT.java:703)

2017-09-08T12:27:38.751509+00:00 app[web.1]: 	at clojure.core$next__4928.invokeStatic(core.clj:64)

2017-09-08T12:27:38.751540+00:00 app[web.1]: 	at clojure.core$last__4970.invokeStatic(core.clj:268)

2017-09-08T12:27:38.751570+00:00 app[web.1]: 	at clojure.core$last__4970.invoke(core.clj:267)

2017-09-08T12:27:38.751602+00:00 app[web.1]: 	at service.routing.directions$partition_by_street_name.invokeStatic(directions.clj:85)

2017-09-08T12:27:38.751633+00:00 app[web.1]: 	at service.routing.directions$partition_by_street_name.invoke(directions.clj:73)

2017-09-08T12:27:38.751672+00:00 app[web.1]: 	at service.routing.directions$route_leg.invokeStatic(directions.clj:137)

2017-09-08T12:27:38.751702+00:00 app[web.1]: 	at service.routing.directions$route_leg.invoke(directions.clj:131)

2017-09-08T12:27:38.751733+00:00 app[web.1]: 	at service.routing.directions$route.invokeStatic(directions.clj:153)

2017-09-08T12:27:38.751765+00:00 app[web.1]: 	at service.routing.directions$route.invoke(directions.clj:148)

2017-09-08T12:27:38.751796+00:00 app[web.1]: 	at service.routing.directions$direction.invokeStatic(directions.clj:185)

2017-09-08T12:27:38.751825+00:00 app[web.1]: 	at service.routing.directions$direction.doInvoke(directions.clj:165)

2017-09-08T12:27:38.751879+00:00 app[web.1]: 	at clojure.lang.RestFn.invoke(RestFn.java:943)

2017-09-08T12:27:38.751912+00:00 app[web.1]: 	at service.routing.server$fn__13941.invokeStatic(server.clj:44)

2017-09-08T12:27:38.751935+00:00 app[web.1]: 	at service.routing.server$fn__13941.invoke(server.clj:30)

2017-09-08T12:27:38.751964+00:00 app[web.1]: 	at compojure.core$wrap_response$fn__2681.invoke(core.clj:158)

2017-09-08T12:27:38.752007+00:00 app[web.1]: 	at compojure.core$pre_init$fn__2732.invoke(core.clj:328)

2017-09-08T12:27:38.752057+00:00 app[web.1]: 	at compojure.api.coercion$wrap_coerce_response$fn__6722.invoke(coercion.clj:92)

2017-09-08T12:27:38.752081+00:00 app[web.1]: 	at compojure.api.middleware$wrap_coercion$fn__10407.invoke(middleware.clj:112)

2017-09-08T12:27:38.752111+00:00 app[web.1]: 	at compojure.core$pre_init$fn__2734$fn__2737.invoke(core.clj:335)

2017-09-08T12:27:38.752141+00:00 app[web.1]: 	at compojure.core$wrap_route_middleware$fn__2665.invoke(core.clj:127)

2017-09-08T12:27:38.752173+00:00 app[web.1]: 	at compojure.core$wrap_route_info$fn__2670.invoke(core.clj:137)

2017-09-08T12:27:38.752205+00:00 app[web.1]: 	at compojure.core$wrap_route_matches$fn__2674.invoke(core.clj:146)

2017-09-08T12:27:38.752237+00:00 app[web.1]: 	at compojure.core$wrap_routes$fn__2744.invoke(core.clj:348)

2017-09-08T12:27:38.752265+00:00 app[web.1]: 	at compojure.api.routes.Route.invoke(routes.clj:85)

2017-09-08T12:27:38.752298+00:00 app[web.1]: 	at compojure.core$routing$fn__2689.invoke(core.clj:185)

2017-09-08T12:27:38.752337+00:00 app[web.1]: 	at clojure.core$some.invokeStatic(core.clj:2681)

2017-09-08T12:27:38.752362+00:00 app[web.1]: 	at clojure.core$some.invoke(core.clj:2672)

2017-09-08T12:27:38.752405+00:00 app[web.1]: 	at compojure.core$routing.invokeStatic(core.clj:185)

2017-09-08T12:27:38.752443+00:00 app[web.1]: 	at compojure.core$routing.doInvoke(core.clj:182)

2017-09-08T12:27:38.752458+00:00 app[web.1]: 	at clojure.lang.RestFn.applyTo(RestFn.java:139)

2017-09-08T12:27:38.752490+00:00 app[web.1]: 	at clojure.core$apply.invokeStatic(core.clj:659)

2017-09-08T12:27:38.752521+00:00 app[web.1]: 	at clojure.core$apply.invoke(core.clj:652)

2017-09-08T12:27:38.752551+00:00 app[web.1]: 	at compojure.core$routes$fn__2693.invoke(core.clj:192)

2017-09-08T12:27:38.752606+00:00 app[web.1]: 	at compojure.api.routes.Route.invoke(routes.clj:85)

2017-09-08T12:27:38.752674+00:00 app[web.1]: 	at ring.swagger.middleware$wrap_swagger_data$fn__10334.invoke(middleware.clj:35)

2017-09-08T12:27:38.752734+00:00 app[web.1]: 	at ring.middleware.http_response$wrap_http_response$fn__6737.invoke(http_response.clj:19)

2017-09-08T12:27:38.752799+00:00 app[web.1]: 	at compojure.api.middleware$wrap_swagger_data$fn__10423.invoke(middleware.clj:175)

2017-09-08T12:27:38.752963+00:00 app[web.1]: 	at compojure.api.middleware$wrap_inject_data$fn__10404.invoke(middleware.clj:101)

2017-09-08T12:27:38.753023+00:00 app[web.1]: 	at muuntaja.middleware$wrap_params$fn__8198.invoke(middleware.clj:51)

2017-09-08T12:27:38.753116+00:00 app[web.1]: 	at compojure.api.middleware$wrap_exceptions$fn__10393.invoke(middleware.clj:67)

2017-09-08T12:27:38.753202+00:00 app[web.1]: 	at muuntaja.middleware$wrap_format_request$fn__8210.invoke(middleware.clj:113)

2017-09-08T12:27:38.753264+00:00 app[web.1]: 	at compojure.api.middleware$wrap_exceptions$fn__10393.invoke(middleware.clj:67)

2017-09-08T12:27:38.753326+00:00 app[web.1]: 	at muuntaja.middleware$wrap_format_response$fn__8214.invoke(middleware.clj:131)

2017-09-08T12:27:38.753388+00:00 app[web.1]: 	at muuntaja.middleware$wrap_format_negotiate$fn__8207.invoke(middleware.clj:95)

2017-09-08T12:27:38.753484+00:00 app[web.1]: 	at ring.middleware.keyword_params$wrap_keyword_params$fn__6771.invoke(keyword_params.clj:36)

2017-09-08T12:27:38.753543+00:00 app[web.1]: 	at ring.middleware.nested_params$wrap_nested_params$fn__6821.invoke(nested_params.clj:89)

2017-09-08T12:27:38.753626+00:00 app[web.1]: 	at ring.middleware.params$wrap_params$fn__6869.invoke(params.clj:67)

2017-09-08T12:27:38.753687+00:00 app[web.1]: 	at compojure.api.middleware$wrap_inject_data$fn__10404.invoke(middleware.clj:101)

2017-09-08T12:27:38.753740+00:00 app[web.1]: 	at compojure.api.routes.Route.invoke(routes.clj:85)

2017-09-08T12:27:38.753796+00:00 app[web.1]: 	at ring.adapter.jetty$proxy_handler$fn__452.invoke(jetty.clj:25)

2017-09-08T12:27:38.753869+00:00 app[web.1]: 	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)

2017-09-08T12:27:38.753933+00:00 app[web.1]: 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)

2017-09-08T12:27:38.753994+00:00 app[web.1]: 	at org.eclipse.jetty.server.Server.handle(Server.java:499)

2017-09-08T12:27:38.754055+00:00 app[web.1]: 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)

2017-09-08T12:27:38.754110+00:00 app[web.1]: 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)

2017-09-08T12:27:38.754161+00:00 app[web.1]: 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)

2017-09-08T12:27:38.754219+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)

2017-09-08T12:27:38.754281+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)

2017-09-08T12:27:38.754375+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by carocad** [comment]
the latest master has already a fix for this. The source of the problem was because src, dst was the same
